name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt || true
        pip install pytest

    - name: Syntax check (.py files)
      run: |
        python3 -m py_compile esb.py
        python3 -m py_compile frontend.py
        python3 -m py_compile service_notification.py
        python3 -m py_compile service_payment.py

    - name: Run tests with pytest
      run: |
        pytest || echo "No tests found, skipping..."

    - name: Check HTML with tidy
      run: |
        sudo apt-get update && sudo apt-get install -y tidy
        tidy -q -e index.html || true
