name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel
          pip install -r microservices_v3/requirements.txt  # Убедись, что все зависимости актуальны

      - name: Install Node.js
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm

      - name: Install htmlhint
        run: |
          sudo npm install -g htmlhint

      - name: Run tests
        run: |
          pip install pytest
          pytest
          mkdir -p reports
          pytest --junitxml=reports/test-report.xml
          
      - name: Save test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test-report.xml
        
      - name: Check HTML
        run: htmlhint index.html
