name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Ubuntu для CI

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r microservices_v3/requirements.txt

      - name: Install Node.js
        run: |
            sudo apt-get update
            sudo apt-get install -y nodejs npm
        
          
      - name: Install htmlhint
        run: |
          sudo npm install -g htmlhint

      - name: Lint code
        run: |
          pip install flake8
          flake8 .

      - name: Run tests
        run: |
          pip install pytest
          pytest

      - name: Check HTML
        run: htmlhint index.html  # Запуск htmlhint
